api_platform:
  formats:
    jsonld: ["application/ld+json"]
    json: ["application/json"]
    html: ["text/html"]
    jsonhal: ["application/hal+json"]
  mapping:
    paths:
      - "%kernel.project_dir%/src/Domain/Model" # default configuration for annotations
